version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=${ASPNETCORE_URL_HTTP};${ASPNETCORE_URL_HTTPS}
      - ConnectionStrings__IndPubConnection=Host=${DB_Host};Database=${DB_Name};Username=${DB_User};Password=${DB_Password}
      - AppSettings__AccessToken=${AppSettings_AccessToken}
      - AppSettings__Issuer=${AppSettings_Issuer}
      - AppSettings__Audience=${AppSettings_Audience}
    ports:
      - "${port_number_1}:${port_number_1}"
      - "${port_number_2}:${port_number_2}"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB_Name}
      POSTGRES_USER: ${DB_User}
      POSTGRES_PASSWORD: ${DB_Password}
    ports:
      - "${DB_Port}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_User} -d ${DB_Name}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

volumes:
  postgres-data:
