version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=${ASPNETCORE_URL_HTTP};${ASPNETCORE_URL_HTTPS}
      - ConnectionStrings__IndPubConnection=Host=${DB__Host};Database=${DB__Name};Username=${DB__User};Password=${DB__Password}
      - AppSettings__AccessToken=${AppSettings__AccessToken}
      - AppSettings__Issuer=${AppSettings__Issuer}
      - AppSettings__Audience=${AppSettings__Audience}
    ports:
      - "${port_number_1}:${port_number_1}"
      - "${port_number_2}:${port_number_2}"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${DB__Name}
      POSTGRES_USER: ${DB__User}
      POSTGRES_PASSWORD: ${DB__Password}
    ports:
      - "${DB__Port}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB__User} -d ${DB__Name}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 40s

volumes:
  postgres-data:
